version: '3.8'

services:
   #MySQL Database Service
  events-database:
   image: mysql:8.0
   container_name: events-database
   environment:
     MYSQL_DATABASE: events_db
     MYSQL_ROOT_PASSWORD: Root12345!
   ports:
     - "3307:3306"
   volumes:
     - mysql-data:/var/lib/mysql
   restart: unless-stopped


  #Spring Boot Application Service
  spring-boot-app:
    build: .
    container_name: events-server
    depends_on:
      - events-database
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://events-database:3306/events_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root12345!
      SPRING_MAIL_USERNAME: ekeszler77@gmail.com
      SPRING_MAIL_PASSWORD: bfhp fmql mjlj uyko
    restart: unless-stopped

  keycloak-server:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak-server
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"

volumes:
  mysql-data:
